<a href="https://colab.research.google.com/github/zohaibkhan523426-design/result-3-rd-semester-/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [ ]:
df = pd.read_csv("titanic.csv")

In [ ]:
df.head()

   Passengerid   Age     Fare  Sex  ...  Embarked  zero.17  zero.18  2urvived
0            1  22.0   7.2500    0  ...       2.0        0        0         0
1            2  38.0  71.2833    1  ...       0.0        0        0         1
2            3  26.0   7.9250    1  ...       2.0        0        0         1
3            4  35.0  53.1000    1  ...       2.0        0        0         1
4            5  35.0   8.0500    0  ...       2.0        0        0         0

[5 rows x 28 columns]

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
df = load_breast_cancer(as_frame=True).frame

In [ ]:
df.head()

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [ ]:
df.target.value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
clf = LogisticRegression()

In [ ]:
x = df.drop(columns=["target"])
y = df.target

In [ ]:
df.shape

(569, 31)

In [ ]:
x_train, x_test,y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
clf.fit(x_train, y_train)

/Users/jacob/courses/SMIT-AI-B4/ml/lr/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
clf.score(x_train, y_train)

0.9538461538461539

In [ ]:
predictions = clf.predict(x_test)

In [ ]:
predictions

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1])

In [ ]:
accuracy_score(y_test, predictions)

0.9649122807017544

In [ ]:
precision_score(y_test, predictions)

0.961038961038961

In [ ]:
recall_score(y_test, predictions)

0.9866666666666667